- name: Install Nginx
  yum:
    name: nginx
    state: present





- name: Install Tomcat
  yum:
    name: tomcat
    state: present

- name: Start Tomcat service
  service:
    name: tomcat
    state: started
    enabled: yes
