- name: Install Nginx
  yum:
    name: nginx
    state: present



- name: Install Java (OpenJDK)
  yum:
    name: default-jdk
    state: present

- name: Install Tomcat
  yum:
    name: tomcat9
    state: present

- name: Start Tomcat service
  service:
    name: tomcat9
    state: started
    enabled: yes
